package edu.ncsu.csc.iTrust2.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.PatientAdvocateAssociation;

/**
 * Repository for interacting with PatientAdvocateAssociation model. Method
 * implementations generated by Spring
 *
 * @author jalong4
 *
 */
public interface PatientAdvocateAssociationRepository extends JpaRepository<PatientAdvocateAssociation, Long> {

}
